import json

path = r'd:\Pribadi\my project web\VOCAVISION\backend\ml_model\Random_Forest_Model_SMK_final.ipynb'

with open(path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Tulis ulang Cell 3 (run_scenario) tanpa SMOTE
new_cell3 = [
    "# ============================================================\n",
    "# LANGKAH 4 & 5: FUNGSI PELATIHAN & EVALUASI (K-FOLD CV)\n",
    "# ============================================================\n",
    "\n",
    "def run_scenario(X, y_cls, y_reg, use_scaler, scenario_name, n_splits=5):\n",
    "    print(f'\\nMenjalankan: {scenario_name} ...')\n",
    "    print(f'  K-Fold: {n_splits}-fold Stratified CV')\n",
    "\n",
    "    skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=RANDOM_STATE)\n",
    "\n",
    "    # Container akumulasi metrik tiap fold\n",
    "    fold_acc, fold_f1, fold_prec, fold_rec, fold_mcc = [], [], [], [], []\n",
    "    fold_mae, fold_rmse, fold_r2                      = [], [], []\n",
    "\n",
    "    best_fold_f1     = -1\n",
    "    best_fold_model  = None\n",
    "    best_fold_scaler = None\n",
    "    best_X_test_fold = None\n",
    "    best_params      = None\n",
    "\n",
    "    # Grid hyperparameter — konservatif untuk data kecil\n",
    "    param_grid_cls = {\n",
    "        'n_estimators'     : [50, 100, 200],\n",
    "        'max_depth'        : [3, 5, 7],\n",
    "        'min_samples_split': [5, 10],\n",
    "        'min_samples_leaf' : [2, 4],\n",
    "        'max_features'     : ['sqrt', 'log2']\n",
    "    }\n",
    "    param_grid_reg = {\n",
    "        'n_estimators'     : [50, 100, 200],\n",
    "        'max_depth'        : [3, 5, 7],\n",
    "        'min_samples_split': [5, 10],\n",
    "        'min_samples_leaf' : [2, 4]\n",
    "    }\n",
    "\n",
    "    for fold_num, (train_idx, test_idx) in enumerate(skf.split(X, y_cls), 1):\n",
    "        X_train_f = X.iloc[train_idx].values\n",
    "        X_test_f  = X.iloc[test_idx].values\n",
    "        y_train_c = y_cls[train_idx]\n",
    "        y_test_c  = y_cls[test_idx]\n",
    "        y_train_r = y_reg[train_idx]\n",
    "        y_test_r  = y_reg[test_idx]\n",
    "\n",
    "        # ── Scaling (fit HANYA di train, transform di test) ──\n",
    "        if use_scaler:\n",
    "            sc        = StandardScaler()\n",
    "            X_train_f = sc.fit_transform(X_train_f)\n",
    "            X_test_f  = sc.transform(X_test_f)\n",
    "        else:\n",
    "            sc = None\n",
    "\n",
    "        # ── Klasifikasi: class_weight='balanced' menangani imbalance ──\n",
    "        # (tanpa SMOTE / ADASYN)\n",
    "        rf_cls = RandomForestClassifier(\n",
    "            criterion='entropy',\n",
    "            class_weight='balanced',\n",
    "            random_state=RANDOM_STATE,\n",
    "            n_jobs=-1\n",
    "        )\n",
    "        grid_cls = GridSearchCV(\n",
    "            rf_cls, param_grid_cls,\n",
    "            cv=3, scoring='f1_macro', n_jobs=-1\n",
    "        )\n",
    "        grid_cls.fit(X_train_f, y_train_c)\n",
    "        best_cls   = grid_cls.best_estimator_\n",
    "        y_pred_cls = best_cls.predict(X_test_f)\n",
    "\n",
    "        # ── Regresi ──\n",
    "        rf_reg   = RandomForestRegressor(random_state=RANDOM_STATE, n_jobs=-1)\n",
    "        grid_reg = GridSearchCV(\n",
    "            rf_reg, param_grid_reg,\n",
    "            cv=3, scoring='neg_mean_absolute_error', n_jobs=-1\n",
    "        )\n",
    "        grid_reg.fit(X_train_f, y_train_r)\n",
    "        y_pred_reg = grid_reg.best_estimator_.predict(X_test_f)\n",
    "\n",
    "        # ── Metrics fold ke-i ──\n",
    "        acc  = accuracy_score(y_test_c, y_pred_cls)\n",
    "        f1   = f1_score(y_test_c, y_pred_cls, average='macro', zero_division=0)\n",
    "        prec = precision_score(y_test_c, y_pred_cls, average='macro', zero_division=0)\n",
    "        rec  = recall_score(y_test_c, y_pred_cls, average='macro', zero_division=0)\n",
    "        mcc  = matthews_corrcoef(y_test_c, y_pred_cls)\n",
    "        mae  = mean_absolute_error(y_test_r, y_pred_reg)\n",
    "        rmse = np.sqrt(mean_squared_error(y_test_r, y_pred_reg))\n",
    "        r2   = r2_score(y_test_r, y_pred_reg)\n",
    "\n",
    "        fold_acc.append(acc);   fold_f1.append(f1);   fold_prec.append(prec)\n",
    "        fold_rec.append(rec);   fold_mcc.append(mcc)\n",
    "        fold_mae.append(mae);   fold_rmse.append(rmse); fold_r2.append(r2)\n",
    "\n",
    "        print(f'  Fold {fold_num}: Acc={acc:.3f}  F1={f1:.3f}  '\n",
    "              f'Prec={prec:.3f}  Rec={rec:.3f}  MCC={mcc:.3f}  '\n",
    "              f'|  MAE={mae:.3f}  RMSE={rmse:.3f}  R2={r2:.3f}')\n",
    "\n",
    "        # Simpan model fold terbaik (berdasarkan F1)\n",
    "        if f1 > best_fold_f1:\n",
    "            best_fold_f1     = f1\n",
    "            best_fold_model  = best_cls\n",
    "            best_fold_scaler = sc\n",
    "            best_X_test_fold = X_test_f\n",
    "            best_params      = grid_cls.best_params_\n",
    "\n",
    "    # ── Rata-rata semua fold ──\n",
    "    def m(lst): return np.mean(lst), np.std(lst)\n",
    "\n",
    "    acc_m,  acc_s  = m(fold_acc)\n",
    "    f1_m,   f1_s   = m(fold_f1)\n",
    "    prec_m, prec_s = m(fold_prec)\n",
    "    rec_m,  rec_s  = m(fold_rec)\n",
    "    mcc_m,  mcc_s  = m(fold_mcc)\n",
    "    mae_m,  mae_s  = m(fold_mae)\n",
    "    rmse_m, rmse_s = m(fold_rmse)\n",
    "    r2_m,   r2_s   = m(fold_r2)\n",
    "\n",
    "    print(f'  ─────────────────────────────────────────────────────────────────')\n",
    "    print(f'  RATA²  : Acc={acc_m:.3f}±{acc_s:.3f}  F1={f1_m:.3f}±{f1_s:.3f}  '\n",
    "          f'Prec={prec_m:.3f}±{prec_s:.3f}  Rec={rec_m:.3f}±{rec_s:.3f}  '\n",
    "          f'MCC={mcc_m:.3f}±{mcc_s:.3f}')\n",
    "    print(f'           MAE={mae_m:.3f}±{mae_s:.3f}  '\n",
    "          f'RMSE={rmse_m:.3f}±{rmse_s:.3f}  R2={r2_m:.3f}±{r2_s:.3f}')\n",
    "    print(f'  Best hyperparams: {best_params}')\n",
    "\n",
    "    # ── SHAP dari model fold terbaik ──\n",
    "    explainer    = shap.TreeExplainer(best_fold_model)\n",
    "    shap_vals    = explainer.shap_values(best_X_test_fold)\n",
    "    classes_list = list(best_fold_model.classes_)\n",
    "    t_idx        = classes_list.index('Beresiko') if 'Beresiko' in classes_list else 0\n",
    "\n",
    "    shap_target = shap_vals[t_idx] if isinstance(shap_vals, list) else (\n",
    "                  shap_vals[:, :, t_idx] if len(shap_vals.shape) == 3 else shap_vals\n",
    "    )\n",
    "    shap_imp = np.abs(shap_target).mean(axis=0)\n",
    "    imp_df   = pd.DataFrame(\n",
    "        {'feature': selected_features, 'importance': shap_imp}\n",
    "    ).sort_values('importance', ascending=False)\n",
    "    top3 = ', '.join(imp_df.head(3)['feature'].tolist())\n",
    "\n",
    "    return {\n",
    "        'Skenario'         : scenario_name,\n",
    "        'Accuracy'         : f'{acc_m:.4f} ± {acc_s:.4f}',\n",
    "        'F1-Macro'         : f'{f1_m:.4f} ± {f1_s:.4f}',\n",
    "        'Precision'        : f'{prec_m:.4f} ± {prec_s:.4f}',\n",
    "        'Recall'           : f'{rec_m:.4f} ± {rec_s:.4f}',\n",
    "        'MCC'              : f'{mcc_m:.4f} ± {mcc_s:.4f}',\n",
    "        'MAE'              : f'{mae_m:.4f} ± {mae_s:.4f}',\n",
    "        'RMSE'             : f'{rmse_m:.4f} ± {rmse_s:.4f}',\n",
    "        'R2'               : f'{r2_m:.4f} ± {r2_s:.4f}',\n",
    "        'Top 3 SHAP'       : top3,\n",
    "        '_f1_float'        : f1_m,\n",
    "        '_mae_float'       : mae_m,\n",
    "        'model'            : best_fold_model,\n",
    "        'scaler'           : best_fold_scaler,\n",
    "        'selected_features': selected_features\n",
    "    }\n",
]

nb['cells'][3]['source'] = new_cell3
nb['cells'][3]['outputs'] = []
nb['cells'][3]['execution_count'] = None

# Hapus import SMOTE dari Cell 0
src0 = nb['cells'][0]['source']
nb['cells'][0]['source'] = [
    line for line in src0
    if 'SMOTE' not in line and 'imblearn' not in line
]
nb['cells'][0]['outputs'] = []
nb['cells'][0]['execution_count'] = None

with open(path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=2)

print("Selesai — SMOTE/ADASYN dihapus dari notebook.")

# Verifikasi
src_all = ''.join([''.join(c['source']) for c in nb['cells']])
print(f"SMOTE masih ada? {'SMOTE' in src_all}")
print(f"ADASYN masih ada? {'ADASYN' in src_all}")
cw_check = "class_weight='balanced'" in src_all
print(f"class_weight balanced masih ada? {cw_check}")
